services:
  db:
    image: postgres:18-trixie
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:?DATABASE_USER is required}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD is required}
      POSTGRES_DB: ${DATABASE_NAME:?DATABASE_NAME is required}
    restart: always
    volumes:
      - type: volume
        source: habit_tracker_db_data
        target: /var/lib/postgresql
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:5432:5432"
  ui:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?PGADMIN_EMAIL is required}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?PGADMIN_PASSWORD is required}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # servers.json で使用する環境変数をpgAdminコンテナに渡す
      DATABASE_NAME: ${DATABASE_NAME:?DATABASE_NAME is required}
      DATABASE_USER: ${DATABASE_USER:?DATABASE_USER is required}
      # pgAdmin に servers.json の場所を教える
      PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers/servers.json
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - habit_tracker_pgadmin_data:/var/lib/pgadmin
      - ./config/servers.json.template:/pgadmin4/servers.json.template
      - ./pgadmin_entrypoint.sh:/pgadmin_entrypoint.sh
    entrypoint: [ "/bin/bash", "/pgadmin_entrypoint.sh" ]
    depends_on:
      - db
volumes:
  habit_tracker_db_data:
  habit_tracker_pgadmin_data:
